# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: db/server.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import List

import betterproto

from ... import client as __client__
from ... import keyval as __keyval__
from ... import similarity as __similarity__
from ...shared import info as __shared_info__


@dataclass(eq=False, repr=False)
class Unit(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class Pong(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ClientList(betterproto.Message):
    clients: List["__client__.ConnectedClient"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class StoreList(betterproto.Message):
    stores: List["StoreInfo"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class InfoServer(betterproto.Message):
    info: "__shared_info__.ServerInfo" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Set(betterproto.Message):
    upsert: "__shared_info__.StoreUpsert" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Get(betterproto.Message):
    entries: List["__keyval__.DbStoreEntry"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class GetSimNEntry(betterproto.Message):
    key: "__keyval__.StoreKey" = betterproto.message_field(1)
    value: "__keyval__.StoreValue" = betterproto.message_field(2)
    similarity: "__similarity__.Similarity" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class GetSimN(betterproto.Message):
    entries: List["GetSimNEntry"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Del(betterproto.Message):
    deleted_count: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class CreateIndex(betterproto.Message):
    created_indexes: int = betterproto.uint64_field(1)


@dataclass(eq=False, repr=False)
class ServerResponse(betterproto.Message):
    unit: "Unit" = betterproto.message_field(1, group="response")
    pong: "Pong" = betterproto.message_field(2, group="response")
    client_list: "ClientList" = betterproto.message_field(3, group="response")
    store_list: "StoreList" = betterproto.message_field(4, group="response")
    info_server: "InfoServer" = betterproto.message_field(5, group="response")
    set: "Set" = betterproto.message_field(6, group="response")
    get: "Get" = betterproto.message_field(7, group="response")
    get_sim_n: "GetSimN" = betterproto.message_field(8, group="response")
    del_: "Del" = betterproto.message_field(9, group="response")
    create_index: "CreateIndex" = betterproto.message_field(10, group="response")


@dataclass(eq=False, repr=False)
class StoreInfo(betterproto.Message):
    name: str = betterproto.string_field(1)
    len: int = betterproto.uint64_field(2)
    size_in_bytes: int = betterproto.uint64_field(3)
