// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: db/server.proto

package server

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	nonlinear "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/algorithm/nonlinear"
	client "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/client"
	keyval "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/keyval"
	info "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/shared/info"
	similarity "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/similarity"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{1}
}

type ClientList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clients []*client.ConnectedClient `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
}

func (x *ClientList) Reset() {
	*x = ClientList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientList) ProtoMessage() {}

func (x *ClientList) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientList.ProtoReflect.Descriptor instead.
func (*ClientList) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{2}
}

func (x *ClientList) GetClients() []*client.ConnectedClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

type StoreList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stores []*StoreInfo `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
}

func (x *StoreList) Reset() {
	*x = StoreList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreList) ProtoMessage() {}

func (x *StoreList) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreList.ProtoReflect.Descriptor instead.
func (*StoreList) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{3}
}

func (x *StoreList) GetStores() []*StoreInfo {
	if x != nil {
		return x.Stores
	}
	return nil
}

type InfoServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *info.ServerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *InfoServer) Reset() {
	*x = InfoServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoServer) ProtoMessage() {}

func (x *InfoServer) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoServer.ProtoReflect.Descriptor instead.
func (*InfoServer) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{4}
}

func (x *InfoServer) GetInfo() *info.ServerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upsert *info.StoreUpsert `protobuf:"bytes,1,opt,name=upsert,proto3" json:"upsert,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{5}
}

func (x *Set) GetUpsert() *info.StoreUpsert {
	if x != nil {
		return x.Upsert
	}
	return nil
}

type Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*keyval.DbStoreEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Get) Reset() {
	*x = Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{6}
}

func (x *Get) GetEntries() []*keyval.DbStoreEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetSimNEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        *keyval.StoreKey       `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value      *keyval.StoreValue     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Similarity *similarity.Similarity `protobuf:"bytes,3,opt,name=similarity,proto3" json:"similarity,omitempty"`
}

func (x *GetSimNEntry) Reset() {
	*x = GetSimNEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSimNEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimNEntry) ProtoMessage() {}

func (x *GetSimNEntry) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimNEntry.ProtoReflect.Descriptor instead.
func (*GetSimNEntry) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetSimNEntry) GetKey() *keyval.StoreKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetSimNEntry) GetValue() *keyval.StoreValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetSimNEntry) GetSimilarity() *similarity.Similarity {
	if x != nil {
		return x.Similarity
	}
	return nil
}

type GetSimN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*GetSimNEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GetSimN) Reset() {
	*x = GetSimN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSimN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimN) ProtoMessage() {}

func (x *GetSimN) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimN.ProtoReflect.Descriptor instead.
func (*GetSimN) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{8}
}

func (x *GetSimN) GetEntries() []*GetSimNEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Del struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedCount uint64 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
}

func (x *Del) Reset() {
	*x = Del{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Del) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Del) ProtoMessage() {}

func (x *Del) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Del.ProtoReflect.Descriptor instead.
func (*Del) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{9}
}

func (x *Del) GetDeletedCount() uint64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type CreateIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedIndexes uint64 `protobuf:"varint,1,opt,name=created_indexes,json=createdIndexes,proto3" json:"created_indexes,omitempty"`
}

func (x *CreateIndex) Reset() {
	*x = CreateIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndex) ProtoMessage() {}

func (x *CreateIndex) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndex.ProtoReflect.Descriptor instead.
func (*CreateIndex) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{10}
}

func (x *CreateIndex) GetCreatedIndexes() uint64 {
	if x != nil {
		return x.CreatedIndexes
	}
	return 0
}

type ServerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ServerResponse_Unit
	//	*ServerResponse_Pong
	//	*ServerResponse_ClientList
	//	*ServerResponse_StoreList
	//	*ServerResponse_InfoServer
	//	*ServerResponse_Set
	//	*ServerResponse_Get
	//	*ServerResponse_GetSimN
	//	*ServerResponse_Del
	//	*ServerResponse_CreateIndex
	//	*ServerResponse_StoreInfo
	Response isServerResponse_Response `protobuf_oneof:"response"`
}

func (x *ServerResponse) Reset() {
	*x = ServerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerResponse) ProtoMessage() {}

func (x *ServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerResponse.ProtoReflect.Descriptor instead.
func (*ServerResponse) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{11}
}

func (m *ServerResponse) GetResponse() isServerResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ServerResponse) GetUnit() *Unit {
	if x, ok := x.GetResponse().(*ServerResponse_Unit); ok {
		return x.Unit
	}
	return nil
}

func (x *ServerResponse) GetPong() *Pong {
	if x, ok := x.GetResponse().(*ServerResponse_Pong); ok {
		return x.Pong
	}
	return nil
}

func (x *ServerResponse) GetClientList() *ClientList {
	if x, ok := x.GetResponse().(*ServerResponse_ClientList); ok {
		return x.ClientList
	}
	return nil
}

func (x *ServerResponse) GetStoreList() *StoreList {
	if x, ok := x.GetResponse().(*ServerResponse_StoreList); ok {
		return x.StoreList
	}
	return nil
}

func (x *ServerResponse) GetInfoServer() *InfoServer {
	if x, ok := x.GetResponse().(*ServerResponse_InfoServer); ok {
		return x.InfoServer
	}
	return nil
}

func (x *ServerResponse) GetSet() *Set {
	if x, ok := x.GetResponse().(*ServerResponse_Set); ok {
		return x.Set
	}
	return nil
}

func (x *ServerResponse) GetGet() *Get {
	if x, ok := x.GetResponse().(*ServerResponse_Get); ok {
		return x.Get
	}
	return nil
}

func (x *ServerResponse) GetGetSimN() *GetSimN {
	if x, ok := x.GetResponse().(*ServerResponse_GetSimN); ok {
		return x.GetSimN
	}
	return nil
}

func (x *ServerResponse) GetDel() *Del {
	if x, ok := x.GetResponse().(*ServerResponse_Del); ok {
		return x.Del
	}
	return nil
}

func (x *ServerResponse) GetCreateIndex() *CreateIndex {
	if x, ok := x.GetResponse().(*ServerResponse_CreateIndex); ok {
		return x.CreateIndex
	}
	return nil
}

func (x *ServerResponse) GetStoreInfo() *StoreInfo {
	if x, ok := x.GetResponse().(*ServerResponse_StoreInfo); ok {
		return x.StoreInfo
	}
	return nil
}

type isServerResponse_Response interface {
	isServerResponse_Response()
}

type ServerResponse_Unit struct {
	Unit *Unit `protobuf:"bytes,1,opt,name=unit,proto3,oneof"`
}

type ServerResponse_Pong struct {
	Pong *Pong `protobuf:"bytes,2,opt,name=pong,proto3,oneof"`
}

type ServerResponse_ClientList struct {
	ClientList *ClientList `protobuf:"bytes,3,opt,name=client_list,json=clientList,proto3,oneof"`
}

type ServerResponse_StoreList struct {
	StoreList *StoreList `protobuf:"bytes,4,opt,name=store_list,json=storeList,proto3,oneof"`
}

type ServerResponse_InfoServer struct {
	InfoServer *InfoServer `protobuf:"bytes,5,opt,name=info_server,json=infoServer,proto3,oneof"`
}

type ServerResponse_Set struct {
	Set *Set `protobuf:"bytes,6,opt,name=set,proto3,oneof"`
}

type ServerResponse_Get struct {
	Get *Get `protobuf:"bytes,7,opt,name=get,proto3,oneof"`
}

type ServerResponse_GetSimN struct {
	GetSimN *GetSimN `protobuf:"bytes,8,opt,name=get_sim_n,json=getSimN,proto3,oneof"`
}

type ServerResponse_Del struct {
	Del *Del `protobuf:"bytes,9,opt,name=del,proto3,oneof"`
}

type ServerResponse_CreateIndex struct {
	CreateIndex *CreateIndex `protobuf:"bytes,10,opt,name=create_index,json=createIndex,proto3,oneof"`
}

type ServerResponse_StoreInfo struct {
	StoreInfo *StoreInfo `protobuf:"bytes,11,opt,name=store_info,json=storeInfo,proto3,oneof"`
}

func (*ServerResponse_Unit) isServerResponse_Response() {}

func (*ServerResponse_Pong) isServerResponse_Response() {}

func (*ServerResponse_ClientList) isServerResponse_Response() {}

func (*ServerResponse_StoreList) isServerResponse_Response() {}

func (*ServerResponse_InfoServer) isServerResponse_Response() {}

func (*ServerResponse_Set) isServerResponse_Response() {}

func (*ServerResponse_Get) isServerResponse_Response() {}

func (*ServerResponse_GetSimN) isServerResponse_Response() {}

func (*ServerResponse_Del) isServerResponse_Response() {}

func (*ServerResponse_CreateIndex) isServerResponse_Response() {}

func (*ServerResponse_StoreInfo) isServerResponse_Response() {}

type StoreInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name             string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Len              uint64                      `protobuf:"varint,2,opt,name=len,proto3" json:"len,omitempty"`
	SizeInBytes      uint64                      `protobuf:"varint,3,opt,name=size_in_bytes,json=sizeInBytes,proto3" json:"size_in_bytes,omitempty"`
	NonLinearIndices []*nonlinear.NonLinearIndex `protobuf:"bytes,4,rep,name=non_linear_indices,json=nonLinearIndices,proto3" json:"non_linear_indices,omitempty"`
	PredicateIndices []string                    `protobuf:"bytes,5,rep,name=predicate_indices,json=predicateIndices,proto3" json:"predicate_indices,omitempty"`
	Dimension        uint32                      `protobuf:"varint,6,opt,name=dimension,proto3" json:"dimension,omitempty"`
}

func (x *StoreInfo) Reset() {
	*x = StoreInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_db_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInfo) ProtoMessage() {}

func (x *StoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_db_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInfo.ProtoReflect.Descriptor instead.
func (*StoreInfo) Descriptor() ([]byte, []int) {
	return file_db_server_proto_rawDescGZIP(), []int{12}
}

func (x *StoreInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StoreInfo) GetLen() uint64 {
	if x != nil {
		return x.Len
	}
	return 0
}

func (x *StoreInfo) GetSizeInBytes() uint64 {
	if x != nil {
		return x.SizeInBytes
	}
	return 0
}

func (x *StoreInfo) GetNonLinearIndices() []*nonlinear.NonLinearIndex {
	if x != nil {
		return x.NonLinearIndices
	}
	return nil
}

func (x *StoreInfo) GetPredicateIndices() []string {
	if x != nil {
		return x.PredicateIndices
	}
	return nil
}

func (x *StoreInfo) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

var File_db_server_proto protoreflect.FileDescriptor

var file_db_server_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x64, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x19, 0x61, 0x6c,
	0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x2f, 0x6e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x61,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x69, 0x6e, 0x66, 0x6f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69,
	0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x06, 0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74,
	0x22, 0x06, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x3f, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x52, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x39, 0x0a, 0x09, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x0a, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22,
	0x37, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x22, 0x35, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12,
	0x2e, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x44, 0x62, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22,
	0x94, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6d, 0x4e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x22, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36,
	0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2e,
	0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x73, 0x69, 0x6d, 0x69,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x22, 0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6d,
	0x4e, 0x12, 0x31, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x69, 0x6d, 0x4e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74,
	0x72, 0x69, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x36, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x22, 0xa7, 0x04, 0x0a, 0x0e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x75,
	0x6e, 0x69, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64, 0x62, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x55, 0x6e, 0x69, 0x74, 0x48, 0x00, 0x52, 0x04, 0x75, 0x6e,
	0x69, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0f, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x50, 0x6f, 0x6e,
	0x67, 0x48, 0x00, 0x52, 0x04, 0x70, 0x6f, 0x6e, 0x67, 0x12, 0x38, 0x0a, 0x0b, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x35, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52,
	0x09, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x38, 0x0a, 0x0b, 0x69, 0x6e,
	0x66, 0x6f, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x49, 0x6e, 0x66, 0x6f,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x6e, 0x66, 0x6f, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x65,
	0x74, 0x48, 0x00, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x03, 0x67, 0x65, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x48, 0x00, 0x52, 0x03, 0x67, 0x65, 0x74, 0x12, 0x30, 0x0a, 0x09,
	0x67, 0x65, 0x74, 0x5f, 0x73, 0x69, 0x6d, 0x5f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x53,
	0x69, 0x6d, 0x4e, 0x48, 0x00, 0x52, 0x07, 0x67, 0x65, 0x74, 0x53, 0x69, 0x6d, 0x4e, 0x12, 0x22,
	0x0a, 0x03, 0x64, 0x65, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x62,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x03, 0x64,
	0x65, 0x6c, 0x12, 0x3b, 0x0a, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78,
	0x48, 0x00, 0x52, 0x0b, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x35, 0x0a, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x0b, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x64, 0x62, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xf3, 0x01, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x03, 0x6c, 0x65, 0x6e, 0x12, 0x22, 0x0a, 0x0d, 0x73, 0x69, 0x7a, 0x65, 0x5f, 0x69,
	0x6e, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x73,
	0x69, 0x7a, 0x65, 0x49, 0x6e, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x51, 0x0a, 0x12, 0x6e, 0x6f,
	0x6e, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74,
	0x68, 0x6d, 0x2e, 0x6e, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x2e, 0x4e, 0x6f, 0x6e,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x10, 0x6e, 0x6f, 0x6e,
	0x4c, 0x69, 0x6e, 0x65, 0x61, 0x72, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x2b, 0x0a,
	0x11, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63, 0x61, 0x74, 0x65, 0x5f, 0x69, 0x6e, 0x64, 0x69, 0x63,
	0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x10, 0x70, 0x72, 0x65, 0x64, 0x69, 0x63,
	0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x64,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x39, 0x36, 0x2f, 0x61,
	0x68, 0x6e, 0x6c, 0x69, 0x63, 0x68, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x61, 0x68, 0x6e, 0x6c, 0x69,
	0x63, 0x68, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x64, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_db_server_proto_rawDescOnce sync.Once
	file_db_server_proto_rawDescData = file_db_server_proto_rawDesc
)

func file_db_server_proto_rawDescGZIP() []byte {
	file_db_server_proto_rawDescOnce.Do(func() {
		file_db_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_db_server_proto_rawDescData)
	})
	return file_db_server_proto_rawDescData
}

var file_db_server_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_db_server_proto_goTypes = []any{
	(*Unit)(nil),                     // 0: db.server.Unit
	(*Pong)(nil),                     // 1: db.server.Pong
	(*ClientList)(nil),               // 2: db.server.ClientList
	(*StoreList)(nil),                // 3: db.server.StoreList
	(*InfoServer)(nil),               // 4: db.server.InfoServer
	(*Set)(nil),                      // 5: db.server.Set
	(*Get)(nil),                      // 6: db.server.Get
	(*GetSimNEntry)(nil),             // 7: db.server.GetSimNEntry
	(*GetSimN)(nil),                  // 8: db.server.GetSimN
	(*Del)(nil),                      // 9: db.server.Del
	(*CreateIndex)(nil),              // 10: db.server.CreateIndex
	(*ServerResponse)(nil),           // 11: db.server.ServerResponse
	(*StoreInfo)(nil),                // 12: db.server.StoreInfo
	(*client.ConnectedClient)(nil),   // 13: client.ConnectedClient
	(*info.ServerInfo)(nil),          // 14: shared.info.ServerInfo
	(*info.StoreUpsert)(nil),         // 15: shared.info.StoreUpsert
	(*keyval.DbStoreEntry)(nil),      // 16: keyval.DbStoreEntry
	(*keyval.StoreKey)(nil),          // 17: keyval.StoreKey
	(*keyval.StoreValue)(nil),        // 18: keyval.StoreValue
	(*similarity.Similarity)(nil),    // 19: similarity.Similarity
	(*nonlinear.NonLinearIndex)(nil), // 20: algorithm.nonlinear.NonLinearIndex
}
var file_db_server_proto_depIdxs = []int32{
	13, // 0: db.server.ClientList.clients:type_name -> client.ConnectedClient
	12, // 1: db.server.StoreList.stores:type_name -> db.server.StoreInfo
	14, // 2: db.server.InfoServer.info:type_name -> shared.info.ServerInfo
	15, // 3: db.server.Set.upsert:type_name -> shared.info.StoreUpsert
	16, // 4: db.server.Get.entries:type_name -> keyval.DbStoreEntry
	17, // 5: db.server.GetSimNEntry.key:type_name -> keyval.StoreKey
	18, // 6: db.server.GetSimNEntry.value:type_name -> keyval.StoreValue
	19, // 7: db.server.GetSimNEntry.similarity:type_name -> similarity.Similarity
	7,  // 8: db.server.GetSimN.entries:type_name -> db.server.GetSimNEntry
	0,  // 9: db.server.ServerResponse.unit:type_name -> db.server.Unit
	1,  // 10: db.server.ServerResponse.pong:type_name -> db.server.Pong
	2,  // 11: db.server.ServerResponse.client_list:type_name -> db.server.ClientList
	3,  // 12: db.server.ServerResponse.store_list:type_name -> db.server.StoreList
	4,  // 13: db.server.ServerResponse.info_server:type_name -> db.server.InfoServer
	5,  // 14: db.server.ServerResponse.set:type_name -> db.server.Set
	6,  // 15: db.server.ServerResponse.get:type_name -> db.server.Get
	8,  // 16: db.server.ServerResponse.get_sim_n:type_name -> db.server.GetSimN
	9,  // 17: db.server.ServerResponse.del:type_name -> db.server.Del
	10, // 18: db.server.ServerResponse.create_index:type_name -> db.server.CreateIndex
	12, // 19: db.server.ServerResponse.store_info:type_name -> db.server.StoreInfo
	20, // 20: db.server.StoreInfo.non_linear_indices:type_name -> algorithm.nonlinear.NonLinearIndex
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_db_server_proto_init() }
func file_db_server_proto_init() {
	if File_db_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_db_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ClientList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StoreList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*InfoServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*GetSimNEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetSimN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*Del); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*CreateIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ServerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_db_server_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*StoreInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_db_server_proto_msgTypes[11].OneofWrappers = []any{
		(*ServerResponse_Unit)(nil),
		(*ServerResponse_Pong)(nil),
		(*ServerResponse_ClientList)(nil),
		(*ServerResponse_StoreList)(nil),
		(*ServerResponse_InfoServer)(nil),
		(*ServerResponse_Set)(nil),
		(*ServerResponse_Get)(nil),
		(*ServerResponse_GetSimN)(nil),
		(*ServerResponse_Del)(nil),
		(*ServerResponse_CreateIndex)(nil),
		(*ServerResponse_StoreInfo)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_db_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_db_server_proto_goTypes,
		DependencyIndexes: file_db_server_proto_depIdxs,
		MessageInfos:      file_db_server_proto_msgTypes,
	}.Build()
	File_db_server_proto = out.File
	file_db_server_proto_rawDesc = nil
	file_db_server_proto_goTypes = nil
	file_db_server_proto_depIdxs = nil
}
