// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file algorithm/algorithm.proto (package algorithm.algorithms, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum algorithm.algorithms.Algorithm
 */
export enum Algorithm {
  /**
   * @generated from enum value: EuclideanDistance = 0;
   */
  EuclideanDistance = 0,

  /**
   * @generated from enum value: DotProductSimilarity = 1;
   */
  DotProductSimilarity = 1,

  /**
   * @generated from enum value: CosineSimilarity = 2;
   */
  CosineSimilarity = 2,

  /**
   * @generated from enum value: KDTree = 3;
   */
  KDTree = 3,

  /**
   * @generated from enum value: HNSW = 4;
   */
  HNSW = 4,
}
// Retrieve enum metadata with: proto3.getEnumType(Algorithm)
proto3.util.setEnumType(Algorithm, "algorithm.algorithms.Algorithm", [
  { no: 0, name: "EuclideanDistance" },
  { no: 1, name: "DotProductSimilarity" },
  { no: 2, name: "CosineSimilarity" },
  { no: 3, name: "KDTree" },
  { no: 4, name: "HNSW" },
]);

/**
 * @generated from enum algorithm.algorithms.DistanceMetric
 */
export enum DistanceMetric {
  /**
   * @generated from enum value: Euclidean = 0;
   */
  Euclidean = 0,

  /**
   * @generated from enum value: DotProduct = 1;
   */
  DotProduct = 1,

  /**
   * @generated from enum value: Cosine = 2;
   */
  Cosine = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(DistanceMetric)
proto3.util.setEnumType(DistanceMetric, "algorithm.algorithms.DistanceMetric", [
  { no: 0, name: "Euclidean" },
  { no: 1, name: "DotProduct" },
  { no: 2, name: "Cosine" },
]);
