// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file shared/cluster.proto (package shared.cluster, syntax proto3)
/* eslint-disable */
// @ts-nocheck

// Public cluster topology types. Surfaced to client SDKs via the eventual
// `ClusterInfo` query on the public DB and AI services. Standalone (non-
// clustered) servers return a single-entry `ClusterInfoResponse` with
// `role = LEADER` so client code is uniform across deployment modes.
//
// Milestone 1 ships the message definitions only — the query/response variant
// additions to db.query / db.server / ai.query / ai.server land in the
// milestones that actually wire them up (M2 for DB, M4 for AI).

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3, protoInt64 } from "@bufbuild/protobuf";

/**
 * @generated from enum shared.cluster.NodeRole
 */
export enum NodeRole {
  /**
   * @generated from enum value: NODE_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NODE_ROLE_LEADER = 1;
   */
  LEADER = 1,

  /**
   * @generated from enum value: NODE_ROLE_FOLLOWER = 2;
   */
  FOLLOWER = 2,

  /**
   * @generated from enum value: NODE_ROLE_LEARNER = 3;
   */
  LEARNER = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(NodeRole)
proto3.util.setEnumType(NodeRole, "shared.cluster.NodeRole", [
  { no: 0, name: "NODE_ROLE_UNSPECIFIED" },
  { no: 1, name: "NODE_ROLE_LEADER" },
  { no: 2, name: "NODE_ROLE_FOLLOWER" },
  { no: 3, name: "NODE_ROLE_LEARNER" },
]);

/**
 * @generated from enum shared.cluster.NodeHealthStatus
 */
export enum NodeHealthStatus {
  /**
   * @generated from enum value: NODE_HEALTH_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: NODE_HEALTH_STATUS_HEALTHY = 1;
   */
  HEALTHY = 1,

  /**
   * @generated from enum value: NODE_HEALTH_STATUS_UNREACHABLE = 2;
   */
  UNREACHABLE = 2,
}
// Retrieve enum metadata with: proto3.getEnumType(NodeHealthStatus)
proto3.util.setEnumType(NodeHealthStatus, "shared.cluster.NodeHealthStatus", [
  { no: 0, name: "NODE_HEALTH_STATUS_UNSPECIFIED" },
  { no: 1, name: "NODE_HEALTH_STATUS_HEALTHY" },
  { no: 2, name: "NODE_HEALTH_STATUS_UNREACHABLE" },
]);

/**
 * @generated from message shared.cluster.ClusterNode
 */
export class ClusterNode extends Message<ClusterNode> {
  /**
   * @generated from field: uint64 node_id = 1;
   */
  nodeId = protoInt64.zero;

  /**
   * Public client-facing service address (`host:port`), the same value the
   * node was started with via `--port`. Clients can connect directly to this
   * address.
   *
   * @generated from field: string addr = 2;
   */
  addr = "";

  /**
   * @generated from field: shared.cluster.NodeRole role = 3;
   */
  role = NodeRole.UNSPECIFIED;

  /**
   * @generated from field: shared.cluster.NodeHealthStatus health = 4;
   */
  health = NodeHealthStatus.UNSPECIFIED;

  /**
   * Current Raft term as observed by this specific node. Unset when the node
   * is unreachable.
   *
   * @generated from field: optional uint64 term = 5;
   */
  term?: bigint;

  /**
   * Last committed log index as observed by this specific node. Unset when
   * the node is unreachable.
   *
   * @generated from field: optional uint64 commit_index = 6;
   */
  commitIndex?: bigint;

  constructor(data?: PartialMessage<ClusterNode>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shared.cluster.ClusterNode";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "node_id", kind: "scalar", T: 4 /* ScalarType.UINT64 */ },
    { no: 2, name: "addr", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "role", kind: "enum", T: proto3.getEnumType(NodeRole) },
    { no: 4, name: "health", kind: "enum", T: proto3.getEnumType(NodeHealthStatus) },
    { no: 5, name: "term", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
    { no: 6, name: "commit_index", kind: "scalar", T: 4 /* ScalarType.UINT64 */, opt: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterNode {
    return new ClusterNode().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterNode {
    return new ClusterNode().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterNode {
    return new ClusterNode().fromJsonString(jsonString, options);
  }

  static equals(
    a: ClusterNode | PlainMessage<ClusterNode> | undefined,
    b: ClusterNode | PlainMessage<ClusterNode> | undefined,
  ): boolean {
    return proto3.util.equals(ClusterNode, a, b);
  }
}

/**
 * @generated from message shared.cluster.ClusterInfoQuery
 */
export class ClusterInfoQuery extends Message<ClusterInfoQuery> {
  constructor(data?: PartialMessage<ClusterInfoQuery>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shared.cluster.ClusterInfoQuery";
  static readonly fields: FieldList = proto3.util.newFieldList(() => []);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterInfoQuery {
    return new ClusterInfoQuery().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterInfoQuery {
    return new ClusterInfoQuery().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ClusterInfoQuery {
    return new ClusterInfoQuery().fromJsonString(jsonString, options);
  }

  static equals(
    a: ClusterInfoQuery | PlainMessage<ClusterInfoQuery> | undefined,
    b: ClusterInfoQuery | PlainMessage<ClusterInfoQuery> | undefined,
  ): boolean {
    return proto3.util.equals(ClusterInfoQuery, a, b);
  }
}

/**
 * @generated from message shared.cluster.ClusterInfoResponse
 */
export class ClusterInfoResponse extends Message<ClusterInfoResponse> {
  /**
   * @generated from field: repeated shared.cluster.ClusterNode nodes = 1;
   */
  nodes: ClusterNode[] = [];

  constructor(data?: PartialMessage<ClusterInfoResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "shared.cluster.ClusterInfoResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "nodes", kind: "message", T: ClusterNode, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ClusterInfoResponse {
    return new ClusterInfoResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ClusterInfoResponse {
    return new ClusterInfoResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): ClusterInfoResponse {
    return new ClusterInfoResponse().fromJsonString(jsonString, options);
  }

  static equals(
    a: ClusterInfoResponse | PlainMessage<ClusterInfoResponse> | undefined,
    b: ClusterInfoResponse | PlainMessage<ClusterInfoResponse> | undefined,
  ): boolean {
    return proto3.util.equals(ClusterInfoResponse, a, b);
  }
}
