[package]
name = "typegen"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde-reflection = "0.3.6"
serde-generate = "0.25.1"
serde_json.workspace = true
ndarray.workspace = true
types = { path = "../types", version = "*" }
clap.workspace = true
