// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file ai/execution_provider.proto (package ai.execution_provider, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * Enum for Execution Providers
 *
 * @generated from enum ai.execution_provider.ExecutionProvider
 */
export enum ExecutionProvider {
  /**
   * @generated from enum value: TENSOR_RT = 0;
   */
  TENSOR_RT = 0,

  /**
   * @generated from enum value: CUDA = 1;
   */
  CUDA = 1,

  /**
   * @generated from enum value: DIRECT_ML = 2;
   */
  DIRECT_ML = 2,

  /**
   * @generated from enum value: CORE_ML = 3;
   */
  CORE_ML = 3,
}
// Retrieve enum metadata with: proto3.getEnumType(ExecutionProvider)
proto3.util.setEnumType(ExecutionProvider, "ai.execution_provider.ExecutionProvider", [
  { no: 0, name: "TENSOR_RT" },
  { no: 1, name: "CUDA" },
  { no: 2, name: "DIRECT_ML" },
  { no: 3, name: "CORE_ML" },
]);
