// This file is @generated by prost-build.
/// Enum for Execution Providers
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ExecutionProvider {
    TensorRt = 0,
    Cuda = 1,
    DirectMl = 2,
    CoreMl = 3,
    /// ROCm execution provider for AMD GPUs (Linux + supported AMD Instinct /
    /// Radeon hardware). Requires the host to have a matching ROCm runtime
    /// installed and the ort/onnxruntime build configured with ROCm support.
    /// Note: upstream onnxruntime removed the ROCm provider in 1.23; for newer
    /// ORT builds prefer MIGRAPHX.
    Rocm = 4,
    /// MIGraphX execution provider for AMD GPUs (Linux + supported AMD Instinct
    /// hardware). AMD's recommended replacement for the ROCm provider in
    /// onnxruntime >= 1.23. Requires the host to have the MIGraphX runtime
    /// installed (ships in AMD's ROCm apt repository).
    Migraphx = 5,
}
impl ExecutionProvider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::TensorRt => "TENSOR_RT",
            Self::Cuda => "CUDA",
            Self::DirectMl => "DIRECT_ML",
            Self::CoreMl => "CORE_ML",
            Self::Rocm => "ROCM",
            Self::Migraphx => "MIGRAPHX",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TENSOR_RT" => Some(Self::TensorRt),
            "CUDA" => Some(Self::Cuda),
            "DIRECT_ML" => Some(Self::DirectMl),
            "CORE_ML" => Some(Self::CoreMl),
            "ROCM" => Some(Self::Rocm),
            "MIGRAPHX" => Some(Self::Migraphx),
            _ => None,
        }
    }
}
