// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file client.proto (package client, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message client.ConnectedClient
 */
export class ConnectedClient extends Message<ConnectedClient> {
  /**
   * @generated from field: string address = 1;
   */
  address = "";

  /**
   * @generated from field: string time_connected = 2;
   */
  timeConnected = "";

  constructor(data?: PartialMessage<ConnectedClient>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "client.ConnectedClient";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "address", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "time_connected", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ConnectedClient {
    return new ConnectedClient().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ConnectedClient {
    return new ConnectedClient().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ConnectedClient {
    return new ConnectedClient().fromJsonString(jsonString, options);
  }

  static equals(
    a: ConnectedClient | PlainMessage<ConnectedClient> | undefined,
    b: ConnectedClient | PlainMessage<ConnectedClient> | undefined,
  ): boolean {
    return proto3.util.equals(ConnectedClient, a, b);
  }
}
