// @generated by protoc-gen-es v1.10.0 with parameter "target=ts"
// @generated from file metadata.proto (package metadata, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from message metadata.MetadataValue
 */
export class MetadataValue extends Message<MetadataValue> {
  /**
   * @generated from oneof metadata.MetadataValue.value
   */
  value:
    | {
        /**
         * @generated from field: string raw_string = 2;
         */
        value: string;
        case: "rawString";
      }
    | {
        /**
         * @generated from field: bytes image = 3;
         */
        value: Uint8Array;
        case: "image";
      }
    | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<MetadataValue>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "metadata.MetadataValue";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 2, name: "raw_string", kind: "scalar", T: 9 /* ScalarType.STRING */, oneof: "value" },
    { no: 3, name: "image", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "value" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MetadataValue {
    return new MetadataValue().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MetadataValue {
    return new MetadataValue().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MetadataValue {
    return new MetadataValue().fromJsonString(jsonString, options);
  }

  static equals(
    a: MetadataValue | PlainMessage<MetadataValue> | undefined,
    b: MetadataValue | PlainMessage<MetadataValue> | undefined,
  ): boolean {
    return proto3.util.equals(MetadataValue, a, b);
  }
}
