// This file is @generated by prost-build.
#[derive(PartialOrd, Ord, Hash, Eq, Clone, PartialEq, ::prost::Message)]
pub struct MetadataValue {
    #[prost(oneof = "metadata_value::Value", tags = "2, 3")]
    pub value: ::core::option::Option<metadata_value::Value>,
}
/// Nested message and enum types in `MetadataValue`.
pub mod metadata_value {
    #[derive(PartialOrd, Ord, Hash, Eq, Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(string, tag = "2")]
        RawString(::prost::alloc::string::String),
        #[prost(bytes, tag = "3")]
        Image(::prost::alloc::vec::Vec<u8>),
    }
}
