// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterNode {
    #[prost(uint64, tag = "1")]
    pub node_id: u64,
    /// Public client-facing service address (`host:port`), the same value the
    /// node was started with via `--port`. Clients can connect directly to this
    /// address.
    #[prost(string, tag = "2")]
    pub addr: ::prost::alloc::string::String,
    #[prost(enumeration = "NodeRole", tag = "3")]
    pub role: i32,
    #[prost(enumeration = "NodeHealthStatus", tag = "4")]
    pub health: i32,
    /// Current Raft term as observed by this specific node. Unset when the node
    /// is unreachable.
    #[prost(uint64, optional, tag = "5")]
    pub term: ::core::option::Option<u64>,
    /// Last committed log index as observed by this specific node. Unset when
    /// the node is unreachable.
    #[prost(uint64, optional, tag = "6")]
    pub commit_index: ::core::option::Option<u64>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClusterInfoQuery {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ClusterInfoResponse {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<ClusterNode>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeRole {
    Unspecified = 0,
    Leader = 1,
    Follower = 2,
    Learner = 3,
}
impl NodeRole {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NODE_ROLE_UNSPECIFIED",
            Self::Leader => "NODE_ROLE_LEADER",
            Self::Follower => "NODE_ROLE_FOLLOWER",
            Self::Learner => "NODE_ROLE_LEARNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "NODE_ROLE_LEADER" => Some(Self::Leader),
            "NODE_ROLE_FOLLOWER" => Some(Self::Follower),
            "NODE_ROLE_LEARNER" => Some(Self::Learner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum NodeHealthStatus {
    Unspecified = 0,
    Healthy = 1,
    Unreachable = 2,
}
impl NodeHealthStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "NODE_HEALTH_STATUS_UNSPECIFIED",
            Self::Healthy => "NODE_HEALTH_STATUS_HEALTHY",
            Self::Unreachable => "NODE_HEALTH_STATUS_UNREACHABLE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "NODE_HEALTH_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "NODE_HEALTH_STATUS_HEALTHY" => Some(Self::Healthy),
            "NODE_HEALTH_STATUS_UNREACHABLE" => Some(Self::Unreachable),
            _ => None,
        }
    }
}
