/* tslint:disable */
/* eslint-disable */
export const __wbg_ahnlichdb_free: (a: number, b: number) => void;
export const ahnlichdb_create_non_linear_algorithm_index: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_create_pred_index: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_create_store: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_del_key: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_del_pred: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_drop_non_linear_algorithm_index: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_drop_pred_index: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_drop_schema: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_drop_store: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_export_snapshot: (a: number) => [number, number, number, number];
export const ahnlichdb_get_key: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_get_pred: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_get_sim_n: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_get_store: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_import_snapshot: (a: number, b: number, c: number) => [number, number];
export const ahnlichdb_list_stores: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_new: () => number;
export const ahnlichdb_set: (a: number, b: number, c: number) => [number, number, number, number];
export const ahnlichdb_upsert: (a: number, b: number, c: number) => [number, number, number, number];
export const init: () => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_start_worker: (a: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
