// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: algorithm/algorithm.proto

package ahnlichclientalgopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Algorithm int32

const (
	Algorithm_EuclideanDistance    Algorithm = 0
	Algorithm_DotProductSimilarity Algorithm = 1
	Algorithm_CosineSimilarity     Algorithm = 2
	Algorithm_KDTree               Algorithm = 3
)

// Enum value maps for Algorithm.
var (
	Algorithm_name = map[int32]string{
		0: "EuclideanDistance",
		1: "DotProductSimilarity",
		2: "CosineSimilarity",
		3: "KDTree",
	}
	Algorithm_value = map[string]int32{
		"EuclideanDistance":    0,
		"DotProductSimilarity": 1,
		"CosineSimilarity":     2,
		"KDTree":               3,
	}
)

func (x Algorithm) Enum() *Algorithm {
	p := new(Algorithm)
	*p = x
	return p
}

func (x Algorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Algorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_algorithm_algorithm_proto_enumTypes[0].Descriptor()
}

func (Algorithm) Type() protoreflect.EnumType {
	return &file_algorithm_algorithm_proto_enumTypes[0]
}

func (x Algorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Algorithm.Descriptor instead.
func (Algorithm) EnumDescriptor() ([]byte, []int) {
	return file_algorithm_algorithm_proto_rawDescGZIP(), []int{0}
}

var File_algorithm_algorithm_proto protoreflect.FileDescriptor

var file_algorithm_algorithm_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x2f, 0x61, 0x6c, 0x67, 0x6f,
	0x72, 0x69, 0x74, 0x68, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x61, 0x6c, 0x67,
	0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x2e, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d,
	0x73, 0x2a, 0x5e, 0x0a, 0x09, 0x41, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x12, 0x15,
	0x0a, 0x11, 0x45, 0x75, 0x63, 0x6c, 0x69, 0x64, 0x65, 0x61, 0x6e, 0x44, 0x69, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x44, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x10, 0x01, 0x12,
	0x14, 0x0a, 0x10, 0x43, 0x6f, 0x73, 0x69, 0x6e, 0x65, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x4b, 0x44, 0x54, 0x72, 0x65, 0x65, 0x10,
	0x03, 0x42, 0x60, 0x5a, 0x5e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x65, 0x76, 0x65, 0x6e, 0x39, 0x36, 0x2f, 0x61, 0x68, 0x6e, 0x6c, 0x69, 0x63, 0x68, 0x2f,
	0x73, 0x64, 0x6b, 0x2f, 0x61, 0x68, 0x6e, 0x6c, 0x69, 0x63, 0x68, 0x2d, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x72,
	0x69, 0x74, 0x68, 0x6d, 0x2f, 0x61, 0x6c, 0x67, 0x6f, 0x72, 0x69, 0x74, 0x68, 0x6d, 0x73, 0x3b,
	0x61, 0x68, 0x6e, 0x6c, 0x69, 0x63, 0x68, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x6c, 0x67,
	0x6f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_algorithm_algorithm_proto_rawDescOnce sync.Once
	file_algorithm_algorithm_proto_rawDescData = file_algorithm_algorithm_proto_rawDesc
)

func file_algorithm_algorithm_proto_rawDescGZIP() []byte {
	file_algorithm_algorithm_proto_rawDescOnce.Do(func() {
		file_algorithm_algorithm_proto_rawDescData = protoimpl.X.CompressGZIP(file_algorithm_algorithm_proto_rawDescData)
	})
	return file_algorithm_algorithm_proto_rawDescData
}

var file_algorithm_algorithm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_algorithm_algorithm_proto_goTypes = []any{
	(Algorithm)(0), // 0: algorithm.algorithms.Algorithm
}
var file_algorithm_algorithm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_algorithm_algorithm_proto_init() }
func file_algorithm_algorithm_proto_init() {
	if File_algorithm_algorithm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_algorithm_algorithm_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_algorithm_algorithm_proto_goTypes,
		DependencyIndexes: file_algorithm_algorithm_proto_depIdxs,
		EnumInfos:         file_algorithm_algorithm_proto_enumTypes,
	}.Build()
	File_algorithm_algorithm_proto = out.File
	file_algorithm_algorithm_proto_rawDesc = nil
	file_algorithm_algorithm_proto_goTypes = nil
	file_algorithm_algorithm_proto_depIdxs = nil
}
