# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: ai/models.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


class AiModel(betterproto.Enum):
    ALL_MINI_LM_L6_V2 = 0
    ALL_MINI_LM_L12_V2 = 1
    BGE_BASE_EN_V15 = 2
    BGE_LARGE_EN_V15 = 3
    RESNET50 = 4
    CLIP_VIT_B32_IMAGE = 5
    CLIP_VIT_B32_TEXT = 6


class AiStoreInputType(betterproto.Enum):
    """Enum for AI Store Input Types"""

    RAW_STRING = 0
    IMAGE = 1
