// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: ai/server.proto

package server

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	models "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/ai/models"
	client "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/client"
	keyval "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/keyval"
	info "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/shared/info"
	similarity "github.com/deven96/ahnlich/sdk/ahnlich-client-go/grpc/similarity"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Unit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Unit) Reset() {
	*x = Unit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unit) ProtoMessage() {}

func (x *Unit) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unit.ProtoReflect.Descriptor instead.
func (*Unit) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{0}
}

type Pong struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Pong) Reset() {
	*x = Pong{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{1}
}

type ClientList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Clients []*client.ConnectedClient `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
}

func (x *ClientList) Reset() {
	*x = ClientList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientList) ProtoMessage() {}

func (x *ClientList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientList.ProtoReflect.Descriptor instead.
func (*ClientList) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{2}
}

func (x *ClientList) GetClients() []*client.ConnectedClient {
	if x != nil {
		return x.Clients
	}
	return nil
}

type StoreList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stores []*AIStoreInfo `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
}

func (x *StoreList) Reset() {
	*x = StoreList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreList) ProtoMessage() {}

func (x *StoreList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreList.ProtoReflect.Descriptor instead.
func (*StoreList) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{3}
}

func (x *StoreList) GetStores() []*AIStoreInfo {
	if x != nil {
		return x.Stores
	}
	return nil
}

type InfoServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info *info.ServerInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *InfoServer) Reset() {
	*x = InfoServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoServer) ProtoMessage() {}

func (x *InfoServer) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoServer.ProtoReflect.Descriptor instead.
func (*InfoServer) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{4}
}

func (x *InfoServer) GetInfo() *info.ServerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type Set struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Upsert *info.StoreUpsert `protobuf:"bytes,1,opt,name=upsert,proto3" json:"upsert,omitempty"`
}

func (x *Set) Reset() {
	*x = Set{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Set) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Set) ProtoMessage() {}

func (x *Set) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Set.ProtoReflect.Descriptor instead.
func (*Set) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{5}
}

func (x *Set) GetUpsert() *info.StoreUpsert {
	if x != nil {
		return x.Upsert
	}
	return nil
}

type GetEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   *keyval.StoreInput `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *keyval.StoreValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *GetEntry) Reset() {
	*x = GetEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntry) ProtoMessage() {}

func (x *GetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntry.ProtoReflect.Descriptor instead.
func (*GetEntry) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{6}
}

func (x *GetEntry) GetKey() *keyval.StoreInput {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetEntry) GetValue() *keyval.StoreValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type Get struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*GetEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Get) Reset() {
	*x = Get{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Get) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Get) ProtoMessage() {}

func (x *Get) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Get.ProtoReflect.Descriptor instead.
func (*Get) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{7}
}

func (x *Get) GetEntries() []*GetEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type GetSimNEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key        *keyval.StoreInput     `protobuf:"bytes,1,opt,name=key,proto3,oneof" json:"key,omitempty"`
	Value      *keyval.StoreValue     `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Similarity *similarity.Similarity `protobuf:"bytes,3,opt,name=similarity,proto3" json:"similarity,omitempty"`
}

func (x *GetSimNEntry) Reset() {
	*x = GetSimNEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSimNEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimNEntry) ProtoMessage() {}

func (x *GetSimNEntry) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimNEntry.ProtoReflect.Descriptor instead.
func (*GetSimNEntry) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{8}
}

func (x *GetSimNEntry) GetKey() *keyval.StoreInput {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetSimNEntry) GetValue() *keyval.StoreValue {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetSimNEntry) GetSimilarity() *similarity.Similarity {
	if x != nil {
		return x.Similarity
	}
	return nil
}

type GetSimN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*GetSimNEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *GetSimN) Reset() {
	*x = GetSimN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSimN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSimN) ProtoMessage() {}

func (x *GetSimN) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSimN.ProtoReflect.Descriptor instead.
func (*GetSimN) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{9}
}

func (x *GetSimN) GetEntries() []*GetSimNEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Del struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DeletedCount uint64 `protobuf:"varint,1,opt,name=deleted_count,json=deletedCount,proto3" json:"deleted_count,omitempty"`
}

func (x *Del) Reset() {
	*x = Del{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Del) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Del) ProtoMessage() {}

func (x *Del) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Del.ProtoReflect.Descriptor instead.
func (*Del) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{10}
}

func (x *Del) GetDeletedCount() uint64 {
	if x != nil {
		return x.DeletedCount
	}
	return 0
}

type CreateIndex struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedIndexes uint64 `protobuf:"varint,1,opt,name=created_indexes,json=createdIndexes,proto3" json:"created_indexes,omitempty"`
}

func (x *CreateIndex) Reset() {
	*x = CreateIndex{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIndex) ProtoMessage() {}

func (x *CreateIndex) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIndex.ProtoReflect.Descriptor instead.
func (*CreateIndex) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{11}
}

func (x *CreateIndex) GetCreatedIndexes() uint64 {
	if x != nil {
		return x.CreatedIndexes
	}
	return 0
}

type AIStoreInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name          string         `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	QueryModel    models.AIModel `protobuf:"varint,2,opt,name=query_model,json=queryModel,proto3,enum=ai.models.AIModel" json:"query_model,omitempty"`
	IndexModel    models.AIModel `protobuf:"varint,3,opt,name=index_model,json=indexModel,proto3,enum=ai.models.AIModel" json:"index_model,omitempty"`
	EmbeddingSize uint64         `protobuf:"varint,4,opt,name=embedding_size,json=embeddingSize,proto3" json:"embedding_size,omitempty"`
}

func (x *AIStoreInfo) Reset() {
	*x = AIStoreInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AIStoreInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIStoreInfo) ProtoMessage() {}

func (x *AIStoreInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIStoreInfo.ProtoReflect.Descriptor instead.
func (*AIStoreInfo) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{12}
}

func (x *AIStoreInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AIStoreInfo) GetQueryModel() models.AIModel {
	if x != nil {
		return x.QueryModel
	}
	return models.AIModel(0)
}

func (x *AIStoreInfo) GetIndexModel() models.AIModel {
	if x != nil {
		return x.IndexModel
	}
	return models.AIModel(0)
}

func (x *AIStoreInfo) GetEmbeddingSize() uint64 {
	if x != nil {
		return x.EmbeddingSize
	}
	return 0
}

type FloatList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloatList []float32 `protobuf:"fixed32,1,rep,packed,name=float_list,json=floatList,proto3" json:"float_list,omitempty"`
}

func (x *FloatList) Reset() {
	*x = FloatList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatList) ProtoMessage() {}

func (x *FloatList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatList.ProtoReflect.Descriptor instead.
func (*FloatList) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{13}
}

func (x *FloatList) GetFloatList() []float32 {
	if x != nil {
		return x.FloatList
	}
	return nil
}

type FloatListList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FloatListList []*FloatList `protobuf:"bytes,1,rep,name=float_list_list,json=floatListList,proto3" json:"float_list_list,omitempty"`
}

func (x *FloatListList) Reset() {
	*x = FloatListList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FloatListList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FloatListList) ProtoMessage() {}

func (x *FloatListList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FloatListList.ProtoReflect.Descriptor instead.
func (*FloatListList) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{14}
}

func (x *FloatListList) GetFloatListList() []*FloatList {
	if x != nil {
		return x.FloatListList
	}
	return nil
}

type SingleInputToEmbedding struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Input     *keyval.StoreInput `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	Embedding *keyval.StoreKey   `protobuf:"bytes,2,opt,name=embedding,proto3" json:"embedding,omitempty"`
}

func (x *SingleInputToEmbedding) Reset() {
	*x = SingleInputToEmbedding{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SingleInputToEmbedding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleInputToEmbedding) ProtoMessage() {}

func (x *SingleInputToEmbedding) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleInputToEmbedding.ProtoReflect.Descriptor instead.
func (*SingleInputToEmbedding) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{15}
}

func (x *SingleInputToEmbedding) GetInput() *keyval.StoreInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *SingleInputToEmbedding) GetEmbedding() *keyval.StoreKey {
	if x != nil {
		return x.Embedding
	}
	return nil
}

type StoreInputToEmbeddingsList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []*SingleInputToEmbedding `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *StoreInputToEmbeddingsList) Reset() {
	*x = StoreInputToEmbeddingsList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ai_server_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StoreInputToEmbeddingsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreInputToEmbeddingsList) ProtoMessage() {}

func (x *StoreInputToEmbeddingsList) ProtoReflect() protoreflect.Message {
	mi := &file_ai_server_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreInputToEmbeddingsList.ProtoReflect.Descriptor instead.
func (*StoreInputToEmbeddingsList) Descriptor() ([]byte, []int) {
	return file_ai_server_proto_rawDescGZIP(), []int{16}
}

func (x *StoreInputToEmbeddingsList) GetValues() []*SingleInputToEmbedding {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_ai_server_proto protoreflect.FileDescriptor

var file_ai_server_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x61, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x09, 0x61, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x1a, 0x0f, 0x61, 0x69,
	0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x6b, 0x65, 0x79,
	0x76, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2f, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x73, 0x69,
	0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x06,
	0x0a, 0x04, 0x55, 0x6e, 0x69, 0x74, 0x22, 0x06, 0x0a, 0x04, 0x50, 0x6f, 0x6e, 0x67, 0x22, 0x3f,
	0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x07,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x22,
	0x3b, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2e, 0x0a, 0x06,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x41, 0x49, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x73, 0x22, 0x39, 0x0a, 0x0a,
	0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x2b, 0x0a, 0x04, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x68, 0x61, 0x72, 0x65,
	0x64, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x37, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x30,
	0x0a, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18,
	0x2e, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x52, 0x06, 0x75, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x22, 0x5a, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x24, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x65, 0x79, 0x76,
	0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x34, 0x0a, 0x03,
	0x47, 0x65, 0x74, 0x12, 0x2d, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69,
	0x65, 0x73, 0x22, 0xa3, 0x01, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6d, 0x4e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x48, 0x00, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x88, 0x01, 0x01, 0x12, 0x28,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x36, 0x0a, 0x0a, 0x73, 0x69, 0x6d, 0x69,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73,
	0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x2e, 0x53, 0x69, 0x6d, 0x69, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x73, 0x69, 0x6d, 0x69, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79,
	0x42, 0x06, 0x0a, 0x04, 0x5f, 0x6b, 0x65, 0x79, 0x22, 0x3c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x53,
	0x69, 0x6d, 0x4e, 0x12, 0x31, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6d, 0x4e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65,
	0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x22, 0x2a, 0x0a, 0x03, 0x44, 0x65, 0x6c, 0x12, 0x23, 0x0a,
	0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x36, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x65, 0x73, 0x22, 0xb2, 0x01, 0x0a, 0x0b, 0x41,
	0x49, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33,
	0x0a, 0x0b, 0x71, 0x75, 0x65, 0x72, 0x79, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x69, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x41, 0x49, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0a, 0x71, 0x75, 0x65, 0x72, 0x79, 0x4d, 0x6f,
	0x64, 0x65, 0x6c, 0x12, 0x33, 0x0a, 0x0b, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x5f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x61, 0x69, 0x2e, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2e, 0x41, 0x49, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x0a, 0x69, 0x6e,
	0x64, 0x65, 0x78, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x25, 0x0a, 0x0e, 0x65, 0x6d, 0x62, 0x65,
	0x64, 0x64, 0x69, 0x6e, 0x67, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0d, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x2a, 0x0a, 0x09, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x02,
	0x52, 0x09, 0x66, 0x6c, 0x6f, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x4d, 0x0a, 0x0d, 0x46,
	0x6c, 0x6f, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x3c, 0x0a, 0x0f,
	0x66, 0x6c, 0x6f, 0x61, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x46, 0x6c, 0x6f, 0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x0d, 0x66, 0x6c, 0x6f,
	0x61, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x72, 0x0a, 0x16, 0x53, 0x69,
	0x6e, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x6f, 0x45, 0x6d, 0x62, 0x65, 0x64,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x28, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x2e,
	0x0a, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6b, 0x65, 0x79, 0x76, 0x61, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x4b, 0x65, 0x79, 0x52, 0x09, 0x65, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x57,
	0x0a, 0x1a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x6f, 0x45, 0x6d,
	0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61,
	0x69, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x54, 0x6f, 0x45, 0x6d, 0x62, 0x65, 0x64, 0x64, 0x69, 0x6e, 0x67, 0x52,
	0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x42, 0x48, 0x5a, 0x46, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76, 0x65, 0x6e, 0x39, 0x36, 0x2f, 0x61, 0x68,
	0x6e, 0x6c, 0x69, 0x63, 0x68, 0x2f, 0x73, 0x64, 0x6b, 0x2f, 0x61, 0x68, 0x6e, 0x6c, 0x69, 0x63,
	0x68, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d, 0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x61, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x3b, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ai_server_proto_rawDescOnce sync.Once
	file_ai_server_proto_rawDescData = file_ai_server_proto_rawDesc
)

func file_ai_server_proto_rawDescGZIP() []byte {
	file_ai_server_proto_rawDescOnce.Do(func() {
		file_ai_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_ai_server_proto_rawDescData)
	})
	return file_ai_server_proto_rawDescData
}

var file_ai_server_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_ai_server_proto_goTypes = []any{
	(*Unit)(nil),                       // 0: ai.server.Unit
	(*Pong)(nil),                       // 1: ai.server.Pong
	(*ClientList)(nil),                 // 2: ai.server.ClientList
	(*StoreList)(nil),                  // 3: ai.server.StoreList
	(*InfoServer)(nil),                 // 4: ai.server.InfoServer
	(*Set)(nil),                        // 5: ai.server.Set
	(*GetEntry)(nil),                   // 6: ai.server.GetEntry
	(*Get)(nil),                        // 7: ai.server.Get
	(*GetSimNEntry)(nil),               // 8: ai.server.GetSimNEntry
	(*GetSimN)(nil),                    // 9: ai.server.GetSimN
	(*Del)(nil),                        // 10: ai.server.Del
	(*CreateIndex)(nil),                // 11: ai.server.CreateIndex
	(*AIStoreInfo)(nil),                // 12: ai.server.AIStoreInfo
	(*FloatList)(nil),                  // 13: ai.server.FloatList
	(*FloatListList)(nil),              // 14: ai.server.FloatListList
	(*SingleInputToEmbedding)(nil),     // 15: ai.server.SingleInputToEmbedding
	(*StoreInputToEmbeddingsList)(nil), // 16: ai.server.StoreInputToEmbeddingsList
	(*client.ConnectedClient)(nil),     // 17: client.ConnectedClient
	(*info.ServerInfo)(nil),            // 18: shared.info.ServerInfo
	(*info.StoreUpsert)(nil),           // 19: shared.info.StoreUpsert
	(*keyval.StoreInput)(nil),          // 20: keyval.StoreInput
	(*keyval.StoreValue)(nil),          // 21: keyval.StoreValue
	(*similarity.Similarity)(nil),      // 22: similarity.Similarity
	(models.AIModel)(0),                // 23: ai.models.AIModel
	(*keyval.StoreKey)(nil),            // 24: keyval.StoreKey
}
var file_ai_server_proto_depIdxs = []int32{
	17, // 0: ai.server.ClientList.clients:type_name -> client.ConnectedClient
	12, // 1: ai.server.StoreList.stores:type_name -> ai.server.AIStoreInfo
	18, // 2: ai.server.InfoServer.info:type_name -> shared.info.ServerInfo
	19, // 3: ai.server.Set.upsert:type_name -> shared.info.StoreUpsert
	20, // 4: ai.server.GetEntry.key:type_name -> keyval.StoreInput
	21, // 5: ai.server.GetEntry.value:type_name -> keyval.StoreValue
	6,  // 6: ai.server.Get.entries:type_name -> ai.server.GetEntry
	20, // 7: ai.server.GetSimNEntry.key:type_name -> keyval.StoreInput
	21, // 8: ai.server.GetSimNEntry.value:type_name -> keyval.StoreValue
	22, // 9: ai.server.GetSimNEntry.similarity:type_name -> similarity.Similarity
	8,  // 10: ai.server.GetSimN.entries:type_name -> ai.server.GetSimNEntry
	23, // 11: ai.server.AIStoreInfo.query_model:type_name -> ai.models.AIModel
	23, // 12: ai.server.AIStoreInfo.index_model:type_name -> ai.models.AIModel
	13, // 13: ai.server.FloatListList.float_list_list:type_name -> ai.server.FloatList
	20, // 14: ai.server.SingleInputToEmbedding.input:type_name -> keyval.StoreInput
	24, // 15: ai.server.SingleInputToEmbedding.embedding:type_name -> keyval.StoreKey
	15, // 16: ai.server.StoreInputToEmbeddingsList.values:type_name -> ai.server.SingleInputToEmbedding
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_ai_server_proto_init() }
func file_ai_server_proto_init() {
	if File_ai_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ai_server_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Unit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Pong); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*ClientList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*StoreList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*InfoServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*Set); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*GetEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*Get); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*GetSimNEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*GetSimN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*Del); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*CreateIndex); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*AIStoreInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*FloatList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*FloatListList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*SingleInputToEmbedding); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ai_server_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*StoreInputToEmbeddingsList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ai_server_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ai_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_server_proto_goTypes,
		DependencyIndexes: file_ai_server_proto_depIdxs,
		MessageInfos:      file_ai_server_proto_msgTypes,
	}.Build()
	File_ai_server_proto = out.File
	file_ai_server_proto_rawDesc = nil
	file_ai_server_proto_goTypes = nil
	file_ai_server_proto_depIdxs = nil
}
