{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ahnlich-db.fullname" . }}-headless
  labels:
    {{- include "ahnlich-db.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: cluster
      port: {{ .Values.cluster.port }}
      targetPort: cluster
      protocol: TCP
  selector:
    {{- include "ahnlich-db.selectorLabels" . | nindent 4 }}
{{- end }}
