// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: ai/execution_provider.proto

package ahnlichclientaipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum for Execution Providers
type ExecutionProvider int32

const (
	ExecutionProvider_TENSOR_RT ExecutionProvider = 0
	ExecutionProvider_CUDA      ExecutionProvider = 1
	ExecutionProvider_DIRECT_ML ExecutionProvider = 2
	ExecutionProvider_CORE_ML   ExecutionProvider = 3
)

// Enum value maps for ExecutionProvider.
var (
	ExecutionProvider_name = map[int32]string{
		0: "TENSOR_RT",
		1: "CUDA",
		2: "DIRECT_ML",
		3: "CORE_ML",
	}
	ExecutionProvider_value = map[string]int32{
		"TENSOR_RT": 0,
		"CUDA":      1,
		"DIRECT_ML": 2,
		"CORE_ML":   3,
	}
)

func (x ExecutionProvider) Enum() *ExecutionProvider {
	p := new(ExecutionProvider)
	*p = x
	return p
}

func (x ExecutionProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_ai_execution_provider_proto_enumTypes[0].Descriptor()
}

func (ExecutionProvider) Type() protoreflect.EnumType {
	return &file_ai_execution_provider_proto_enumTypes[0]
}

func (x ExecutionProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionProvider.Descriptor instead.
func (ExecutionProvider) EnumDescriptor() ([]byte, []int) {
	return file_ai_execution_provider_proto_rawDescGZIP(), []int{0}
}

var File_ai_execution_provider_proto protoreflect.FileDescriptor

var file_ai_execution_provider_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x69, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x61,
	0x69, 0x2e, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x2a, 0x48, 0x0a, 0x11, 0x45, 0x78, 0x65, 0x63, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x45, 0x4e,
	0x53, 0x4f, 0x52, 0x5f, 0x52, 0x54, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x55, 0x44, 0x41,
	0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x49, 0x52, 0x45, 0x43, 0x54, 0x5f, 0x4d, 0x4c, 0x10,
	0x02, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x4f, 0x52, 0x45, 0x5f, 0x4d, 0x4c, 0x10, 0x03, 0x42, 0x5f,
	0x5a, 0x5d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x65, 0x76,
	0x65, 0x6e, 0x39, 0x36, 0x2f, 0x61, 0x68, 0x6e, 0x6c, 0x69, 0x63, 0x68, 0x2f, 0x73, 0x64, 0x6b,
	0x2f, 0x61, 0x68, 0x6e, 0x6c, 0x69, 0x63, 0x68, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d,
	0x67, 0x6f, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x61, 0x69, 0x2f, 0x65, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x3b, 0x61, 0x68,
	0x6e, 0x6c, 0x69, 0x63, 0x68, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x61, 0x69, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ai_execution_provider_proto_rawDescOnce sync.Once
	file_ai_execution_provider_proto_rawDescData = file_ai_execution_provider_proto_rawDesc
)

func file_ai_execution_provider_proto_rawDescGZIP() []byte {
	file_ai_execution_provider_proto_rawDescOnce.Do(func() {
		file_ai_execution_provider_proto_rawDescData = protoimpl.X.CompressGZIP(file_ai_execution_provider_proto_rawDescData)
	})
	return file_ai_execution_provider_proto_rawDescData
}

var file_ai_execution_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ai_execution_provider_proto_goTypes = []any{
	(ExecutionProvider)(0), // 0: ai.execution_provider.ExecutionProvider
}
var file_ai_execution_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_execution_provider_proto_init() }
func file_ai_execution_provider_proto_init() {
	if File_ai_execution_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ai_execution_provider_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_execution_provider_proto_goTypes,
		DependencyIndexes: file_ai_execution_provider_proto_depIdxs,
		EnumInfos:         file_ai_execution_provider_proto_enumTypes,
	}.Build()
	File_ai_execution_provider_proto = out.File
	file_ai_execution_provider_proto_rawDesc = nil
	file_ai_execution_provider_proto_goTypes = nil
	file_ai_execution_provider_proto_depIdxs = nil
}
