[package]
name = "grpc_types"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.12.3"
prost = "0.13"
prost-types = "0.13"

[build-dependencies]
prost-build = "0.13.4"
tonic-build = "0.12.3"
walkdir = "2.5.0"
