import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    "overview",
    {
      type: 'category',
      label: '🚀 Getting Started',
      link: {
        type: 'doc',
        id: 'getting-started/getting-started',
      },
      items: [
        'getting-started/installation',
        'getting-started/usage',
        'getting-started/comparison-with-other-tools',
        'getting-started/next-steps',
      ],
    },
    {
      type: 'category',
      label: '🧩 Components',
      link: {
        type: 'doc',
        id: 'components/components',
      },
      items: [
        {
          type: 'category',
          label: '📟 Ahnlich CLI',
          link: {
            type: 'doc',
            id: 'components/ahnlich-cli/ahnlich-cli'
          },
          items: [ 
            'components/ahnlich-cli/overview',
            'components/ahnlich-cli/reference',
            'components/ahnlich-cli/advanced'
          ],
        },
        {
          type: 'category',
          label: '🗄️ Ahnlich DB',
          link: {
            type: 'doc',
            id: 'components/ahnlich-db/ahnlich-db'
          },
          items: [ 
            'components/ahnlich-db/overview',
            'components/ahnlich-db/reference',
            'components/ahnlich-db/advanced'
          ],
        },
        {
          type: 'category',
          label: '🤖 Ahnlich AI',
          link: {
            type: 'doc',
            id: 'components/ahnlich-ai/ahnlich-ai' 
          },
          items: [ 
            'components/ahnlich-ai/overview',
            'components/ahnlich-ai/reference',
            'components/ahnlich-ai/advanced',
            'components/ahnlich-ai/persistence-for-ahnlich-db-and-ahnlich-ai'
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '📚 Client Libraries',
      items: [
        {
          type: 'autogenerated',
          dirName: 'client-libraries',
        },
      ],
    },
    {
      type: 'category',
      label: '⚡Ahnlich in production',
      items: [
        {
          type: 'autogenerated',
          dirName: 'ahnlich-in-production',
        },
      ],
    },
    "architecture",
    "community",
  ],
};

export default sidebars;
