import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import { sbIcon } from './src/sidebarIcons';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Prisma-style docs IA: each top tab (see src/components/DocsSubnav) maps to
 * its own dedicated sidebar so the left menu only shows that section's pages.
 */
const sidebars: SidebarsConfig = {
  // ---- Getting Started tab ------------------------------------------------
  gettingStartedSidebar: [
    {
      type: 'html',
      value: 'Getting started',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    { type: 'doc', id: 'overview', label: 'What is Ahnlich?' },
    'getting-started/installation',
    {
      type: 'category',
      label: 'Quickstart',
      link: { type: 'doc', id: 'getting-started/quickstart' },
      items: [
        'getting-started/quickstart-ai',
        'getting-started/quickstart-db',
      ],
    },
    'getting-started/usage',
    'getting-started/comparison-with-other-tools',
    {
      type: 'html',
      value: 'Guides',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Concepts',
      customProps: sbIcon('book'),
      link: { type: 'doc', id: 'concepts/concepts' },
      items: [
        'concepts/data-model',
        'concepts/vectors',
        'concepts/schemas',
        'concepts/metadata',
        'concepts/similarity-metrics',
        {
          type: 'category',
          label: 'Vector index',
          customProps: sbIcon('layers'),
          link: { type: 'doc', id: 'concepts/vector-index' },
          items: [
            'concepts/vector-index/exact-search',
            'concepts/vector-index/hnsw',
          ],
        },
        'concepts/ai-and-embeddings',
      ],
    },
    {
      type: 'category',
      label: 'Stores',
      customProps: sbIcon('database'),
      link: { type: 'doc', id: 'stores/stores' },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Server operations',
          items: [
            'stores/ping',
            'stores/info-server',
            'stores/list-connected-clients',
          ],
        },
        {
          type: 'category',
          label: 'Store operations',
          items: [
            'stores/create-store',
            'stores/list-stores',
            'stores/get-store',
            'stores/drop-store',
          ],
        },
        {
          type: 'category',
          label: 'Indexes',
          items: [
            'stores/create-predicate-index',
            'stores/drop-predicate-index',
            'stores/create-non-linear-algx',
            'stores/drop-non-linear-algx',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Data operations',
      customProps: sbIcon('code'),
      items: [
        'stores/set',
        'stores/upsert',
        'stores/get-key',
        'stores/get-simn',
        'stores/get-by-predicate',
        'stores/delete-key',
        'stores/delete-predicate',
      ],
    },
    {
      type: 'link',
      label: 'Client libraries',
      href: '/docs/client-libraries',
    },
    'getting-started/ai-friendly',
  ],

  // ---- Vector DB tab ------------------------------------------------------
  vectorDbSidebar: [
    {
      type: 'html',
      value: 'Introduction',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    { type: 'doc', id: 'components/ahnlich-db/ahnlich-db', label: 'Overview' },
    'components/ahnlich-db/installation',
    'components/ahnlich-db/use-cases',
    {
      type: 'html',
      value: 'Reference',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Server & system',
      items: [
        'components/ahnlich-db/reference/ping',
        'components/ahnlich-db/reference/infoserver',
        'components/ahnlich-db/reference/list-connected-clients',
      ],
    },
    {
      type: 'category',
      label: 'Store management',
      items: [
        'components/ahnlich-db/reference/list-stores',
        'components/ahnlich-db/reference/get-store',
        'components/ahnlich-db/reference/create-store',
        'components/ahnlich-db/reference/drop-store',
        'components/ahnlich-db/reference/drop-schema',
      ],
    },
    {
      type: 'category',
      label: 'Data operations',
      items: [
        'components/ahnlich-db/reference/set',
        'components/ahnlich-db/reference/upsert',
        'components/ahnlich-db/reference/delete-key',
        'components/ahnlich-db/reference/delete-predicate',
      ],
    },
    {
      type: 'category',
      label: 'Query & retrieval',
      items: [
        'components/ahnlich-db/reference/get-sim-n',
        'components/ahnlich-db/reference/get-key',
        'components/ahnlich-db/reference/get-by-predicate',
      ],
    },
    {
      type: 'category',
      label: 'Index management',
      items: [
        'components/ahnlich-db/reference/create-predicate-index',
        'components/ahnlich-db/reference/drop-predicate-index',
        'components/ahnlich-db/reference/create-non-linear-index',
        'components/ahnlich-db/reference/drop-non-linear-index',
      ],
    },
    'components/ahnlich-db/reference/sdk-mapping',
    {
      type: 'category',
      label: 'Advanced',
      link: {type: 'doc', id: 'components/ahnlich-db/advanced'},
      items: [
        'components/ahnlich-db/advanced/similarity-algorithms',
        'components/ahnlich-db/advanced/choosing-and-performance',
        'components/ahnlich-db/advanced/command-deep-dive',
        'components/ahnlich-db/advanced/end-to-end-flow',
      ],
    },
  ],

  // ---- AI tab -------------------------------------------------------------
  aiSidebar: [
    {
      type: 'html',
      value: 'Introduction',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    { type: 'doc', id: 'components/ahnlich-ai/ahnlich-ai', label: 'Overview' },
    'components/ahnlich-ai/setup-config',
    'components/ahnlich-ai/use-cases',
    {
      type: 'html',
      value: 'Reference',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Server & system',
      items: [
        'components/ahnlich-ai/reference/ping',
        'components/ahnlich-ai/reference/infoserver',
      ],
    },
    {
      type: 'category',
      label: 'Store management',
      items: [
        'components/ahnlich-ai/reference/list-stores',
        'components/ahnlich-ai/reference/get-store',
        'components/ahnlich-ai/reference/create-store',
        'components/ahnlich-ai/reference/drop-store',
        'components/ahnlich-ai/reference/drop-schema',
      ],
    },
    {
      type: 'category',
      label: 'Data operations',
      items: [
        'components/ahnlich-ai/reference/set',
        'components/ahnlich-ai/reference/upsert',
        'components/ahnlich-ai/reference/delete-key',
      ],
    },
    {
      type: 'category',
      label: 'Query & retrieval',
      items: [
        'components/ahnlich-ai/reference/get-sim-n',
        'components/ahnlich-ai/reference/get-by-predicate',
        'components/ahnlich-ai/reference/get-key',
      ],
    },
    {
      type: 'category',
      label: 'Index management',
      items: [
        'components/ahnlich-ai/reference/create-predicate-index',
        'components/ahnlich-ai/reference/drop-predicate-index',
        'components/ahnlich-ai/reference/create-non-linear-index',
        'components/ahnlich-ai/reference/drop-non-linear-index',
      ],
    },
    'components/ahnlich-ai/reference/sdk-mapping',
    {
      type: 'category',
      label: 'Advanced',
      link: {type: 'doc', id: 'components/ahnlich-ai/advanced'},
      items: [
        'components/ahnlich-ai/advanced/models',
        'components/ahnlich-ai/advanced/model-constraints',
        'components/ahnlich-ai/advanced/code-search',
        'components/ahnlich-ai/advanced/model-parameters',
        'components/ahnlich-ai/advanced/embedding-metadata',
      ],
    },
    'components/ahnlich-ai/deep-dive',
  ],

  // ---- CLI tab ------------------------------------------------------------
  cliSidebar: [
    {
      type: 'html',
      value: 'Introduction',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    { type: 'doc', id: 'components/ahnlich-cli/ahnlich-cli', label: 'Overview' },
    'components/ahnlich-cli/installation',
    {
      type: 'html',
      value: 'Commands',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'DB commands',
      link: { type: 'doc', id: 'components/ahnlich-cli/db-commands' },
      items: [
        'components/ahnlich-cli/db-commands/ping',
        'components/ahnlich-cli/db-commands/infoserver',
        'components/ahnlich-cli/db-commands/list-stores',
        'components/ahnlich-cli/db-commands/create-store',
        'components/ahnlich-cli/db-commands/set',
        'components/ahnlich-cli/db-commands/upsert',
        'components/ahnlich-cli/db-commands/get-key',
        'components/ahnlich-cli/db-commands/get-pred',
        'components/ahnlich-cli/db-commands/delete-key',
        'components/ahnlich-cli/db-commands/create-predicate-index',
        'components/ahnlich-cli/db-commands/drop-predicate-index',
        'components/ahnlich-cli/db-commands/create-non-linear-index',
        'components/ahnlich-cli/db-commands/drop-non-linear-index',
        'components/ahnlich-cli/db-commands/drop-store',
        'components/ahnlich-cli/db-commands/drop-schema',
      ],
    },
    {
      type: 'category',
      label: 'AI commands',
      link: { type: 'doc', id: 'components/ahnlich-cli/ai-commands' },
      items: [
        'components/ahnlich-cli/ai-commands/ping',
        'components/ahnlich-cli/ai-commands/infoserver',
        'components/ahnlich-cli/ai-commands/list-stores',
        'components/ahnlich-cli/ai-commands/create-store',
        'components/ahnlich-cli/ai-commands/set',
        'components/ahnlich-cli/ai-commands/upsert',
        'components/ahnlich-cli/ai-commands/get-sim-n',
        'components/ahnlich-cli/ai-commands/get-pred',
        'components/ahnlich-cli/ai-commands/delete-key',
        'components/ahnlich-cli/ai-commands/create-predicate-index',
        'components/ahnlich-cli/ai-commands/drop-predicate-index',
        'components/ahnlich-cli/ai-commands/create-non-linear-index',
        'components/ahnlich-cli/ai-commands/drop-non-linear-index',
        'components/ahnlich-cli/ai-commands/drop-store',
        'components/ahnlich-cli/ai-commands/drop-schema',
      ],
    },
  ],

  // ---- Clients tab --------------------------------------------------------
  clientsSidebar: [
    {
      type: 'html',
      value: 'Client Libraries',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    {
      type: 'doc',
      id: 'client-libraries/client-libraries',
      label: 'Overview',
    },
    'client-libraries/schema-support',
    {
      type: 'category',
      label: 'Python',
      link: { type: 'doc', id: 'client-libraries/python/python' },
      customProps: {
        iconLight: '/img/python_logo.png',
        iconDark: '/img/python-logo.png',
        iconType: 'img',
      },
      items: [
        'client-libraries/python/python-specific-resources',
        {
          type: 'category',
          label: 'Request DB',
          link: { type: 'doc', id: 'client-libraries/python/request-db/request-db' },
          items: [
            'client-libraries/python/request-db/ping',
            'client-libraries/python/request-db/info-server',
            'client-libraries/python/request-db/list-connected-clients',
            'client-libraries/python/request-db/list-stores',
            'client-libraries/python/request-db/get-store',
            'client-libraries/python/request-db/create-store',
            'client-libraries/python/request-db/set',
            'client-libraries/python/request-db/upsert',
            'client-libraries/python/request-db/get-simn',
            'client-libraries/python/request-db/get-key',
            'client-libraries/python/request-db/get-by-predicate',
            'client-libraries/python/request-db/create-predicate-index',
            'client-libraries/python/request-db/drop-predicate-index',
            'client-libraries/python/request-db/delete-key',
            'client-libraries/python/request-db/delete-predicate',
            'client-libraries/python/request-db/drop-store',
            'client-libraries/python/request-db/create-non-linear-algx',
            'client-libraries/python/request-db/drop-non-linear-algx',
          ],
        },
        {
          type: 'category',
          label: 'Request AI',
          link: { type: 'doc', id: 'client-libraries/python/request-ai/request-ai' },
          items: [
            'client-libraries/python/request-ai/ping',
            'client-libraries/python/request-ai/info-server',
            'client-libraries/python/request-ai/list-connected-clients',
            'client-libraries/python/request-ai/list-stores',
            'client-libraries/python/request-ai/get-store',
            'client-libraries/python/request-ai/create-store',
            'client-libraries/python/request-ai/set',
            'client-libraries/python/request-ai/upsert',
            'client-libraries/python/request-ai/get-simn',
            'client-libraries/python/request-ai/get-key',
            'client-libraries/python/request-ai/get-by-predicate',
            'client-libraries/python/request-ai/create-predicate-index',
            'client-libraries/python/request-ai/drop-predicate-index',
            'client-libraries/python/request-ai/delete-key',
            'client-libraries/python/request-ai/delete-predicate',
            'client-libraries/python/request-ai/drop-store',
            'client-libraries/python/request-ai/create-non-linear-algx',
            'client-libraries/python/request-ai/drop-non-linear-algx',
            'client-libraries/python/request-ai/purge-stores',
          ],
        },
        'client-libraries/python/bulk-requests',
        'client-libraries/python/type-meanings',
      ],
    },
    {
      type: 'category',
      label: 'Node.js',
      link: { type: 'doc', id: 'client-libraries/node/node' },
      customProps: { icon: '/img/nodejs-logo.png', iconType: 'img' },
      items: [
        'client-libraries/node/node-specific-resources',
        {
          type: 'category',
          label: 'Request DB',
          link: { type: 'doc', id: 'client-libraries/node/request-db/request-db' },
          items: [
            'client-libraries/node/request-db/ping',
            'client-libraries/node/request-db/info-server',
            'client-libraries/node/request-db/list-connected-clients',
            'client-libraries/node/request-db/list-stores',
            'client-libraries/node/request-db/get-store',
            'client-libraries/node/request-db/create-store',
            'client-libraries/node/request-db/set',
            'client-libraries/node/request-db/upsert',
            'client-libraries/node/request-db/get-simn',
            'client-libraries/node/request-db/get-key',
            'client-libraries/node/request-db/get-by-predicate',
            'client-libraries/node/request-db/create-predicate-index',
            'client-libraries/node/request-db/drop-predicate-index',
            'client-libraries/node/request-db/create-non-linear-algx',
            'client-libraries/node/request-db/drop-non-linear-algx',
            'client-libraries/node/request-db/delete-key',
            'client-libraries/node/request-db/delete-predicate',
            'client-libraries/node/request-db/drop-store',
          ],
        },
        {
          type: 'category',
          label: 'Request AI',
          link: { type: 'doc', id: 'client-libraries/node/request-ai/request-ai' },
          items: [
            'client-libraries/node/request-ai/ping',
            'client-libraries/node/request-ai/info-server',
            'client-libraries/node/request-ai/list-connected-clients',
            'client-libraries/node/request-ai/list-stores',
            'client-libraries/node/request-ai/get-store',
            'client-libraries/node/request-ai/create-store',
            'client-libraries/node/request-ai/set',
            'client-libraries/node/request-ai/upsert',
            'client-libraries/node/request-ai/get-simn',
            'client-libraries/node/request-ai/get-key',
            'client-libraries/node/request-ai/get-by-predicate',
            'client-libraries/node/request-ai/create-predicate-index',
            'client-libraries/node/request-ai/drop-predicate-index',
            'client-libraries/node/request-ai/create-non-linear-algx',
            'client-libraries/node/request-ai/drop-non-linear-algx',
            'client-libraries/node/request-ai/delete-key',
            'client-libraries/node/request-ai/delete-predicate',
            'client-libraries/node/request-ai/drop-store',
            'client-libraries/node/request-ai/purge-stores',
          ],
        },
        'client-libraries/node/tracing',
        'client-libraries/node/type-meanings',
      ],
    },
    {
      type: 'category',
      label: 'Go',
      link: { type: 'doc', id: 'client-libraries/go/go' },
      customProps: { icon: '/img/go.png', iconType: 'img' },
      items: [
        'client-libraries/go/go-specific-resources',
        {
          type: 'category',
          label: 'Request DB',
          link: { type: 'doc', id: 'client-libraries/go/request-db/request-db' },
          items: [
            'client-libraries/go/request-db/ping',
            'client-libraries/go/request-db/info-server',
            'client-libraries/go/request-db/list-stores',
            'client-libraries/go/request-db/get-store',
            'client-libraries/go/request-db/create-store',
            'client-libraries/go/request-db/set',
            'client-libraries/go/request-db/upsert',
            'client-libraries/go/request-db/get-simn',
            'client-libraries/go/request-db/get-key',
            'client-libraries/go/request-db/get-by-predicate',
            'client-libraries/go/request-db/create-predicate-index',
            'client-libraries/go/request-db/drop-predicate-index',
            'client-libraries/go/request-db/delete-key',
            'client-libraries/go/request-db/drop-store',
            'client-libraries/go/request-db/list-connected-clients',
            'client-libraries/go/request-db/create-non-linear-algx',
            'client-libraries/go/request-db/drop-non-linear-algx',
            'client-libraries/go/request-db/delete-predicate',
          ],
        },
        {
          type: 'category',
          label: 'Request AI',
          link: { type: 'doc', id: 'client-libraries/go/request-ai/request-ai' },
          items: [
            'client-libraries/go/request-ai/ping',
            'client-libraries/go/request-ai/info-server',
            'client-libraries/go/request-ai/list-connected-clients',
            'client-libraries/go/request-ai/list-stores',
            'client-libraries/go/request-ai/get-store',
            'client-libraries/go/request-ai/create-store',
            'client-libraries/go/request-ai/set',
            'client-libraries/go/request-ai/upsert',
            'client-libraries/go/request-ai/get-simn',
            'client-libraries/go/request-ai/get-key',
            'client-libraries/go/request-ai/get-by-predicate',
            'client-libraries/go/request-ai/create-predicate-index',
            'client-libraries/go/request-ai/drop-predicate-index',
            'client-libraries/go/request-ai/delete-key',
            'client-libraries/go/request-ai/delete-predicate',
            'client-libraries/go/request-ai/drop-store',
            'client-libraries/go/request-ai/create-non-linear-algx',
            'client-libraries/go/request-ai/drop-non-linear-algx',
            'client-libraries/go/request-ai/purge-stores',
          ],
        },
        'client-libraries/go/bulk-requests',
        'client-libraries/go/type-meanings',
      ],
    },
    {
      type: 'category',
      label: 'Rust',
      link: { type: 'doc', id: 'client-libraries/rust/rust' },
      customProps: {
        iconLight: '/img/rust.png',
        iconDark: '/img/rust-logo.png',
        iconType: 'img',
      },
      items: [
        'client-libraries/rust/rust-specific-resources',
        {
          type: 'category',
          label: 'Request DB',
          link: { type: 'doc', id: 'client-libraries/rust/request-db/request-db' },
          items: [
            'client-libraries/rust/request-db/ping',
            'client-libraries/rust/request-db/info-server',
            'client-libraries/rust/request-db/list-connected-clients',
            'client-libraries/rust/request-db/list-stores',
            'client-libraries/rust/request-db/get-store',
            'client-libraries/rust/request-db/create-store',
            'client-libraries/rust/request-db/set',
            'client-libraries/rust/request-db/upsert',
            'client-libraries/rust/request-db/get-simn',
            'client-libraries/rust/request-db/get-key',
            'client-libraries/rust/request-db/get-by-predicate',
            'client-libraries/rust/request-db/create-predicate-index',
            'client-libraries/rust/request-db/drop-predicate-index',
            'client-libraries/rust/request-db/delete-key',
            'client-libraries/rust/request-db/delete-predicate',
            'client-libraries/rust/request-db/drop-store',
            'client-libraries/rust/request-db/create-non-linear-algx',
            'client-libraries/rust/request-db/drop-non-linear-algx',
          ],
        },
        {
          type: 'category',
          label: 'Request AI',
          link: { type: 'doc', id: 'client-libraries/rust/request-ai/request-ai' },
          items: [
            'client-libraries/rust/request-ai/ping',
            'client-libraries/rust/request-ai/info-server',
            'client-libraries/rust/request-ai/list-connected-clients',
            'client-libraries/rust/request-ai/list-stores',
            'client-libraries/rust/request-ai/get-store',
            'client-libraries/rust/request-ai/create-store',
            'client-libraries/rust/request-ai/set',
            'client-libraries/rust/request-ai/upsert',
            'client-libraries/rust/request-ai/get-simn',
            'client-libraries/rust/request-ai/get-key',
            'client-libraries/rust/request-ai/get-by-predicate',
            'client-libraries/rust/request-ai/create-predicate-index',
            'client-libraries/rust/request-ai/drop-predicate-index',
            'client-libraries/rust/request-ai/delete-key',
            'client-libraries/rust/request-ai/delete-predicate',
            'client-libraries/rust/request-ai/drop-store',
            'client-libraries/rust/request-ai/create-non-linear-algx',
            'client-libraries/rust/request-ai/drop-non-linear-algx',
            'client-libraries/rust/request-ai/new',
            'client-libraries/rust/request-ai/purge-stores',
          ],
        },
        'client-libraries/rust/pipeline',
        'client-libraries/rust/types-and-utilities',
        'client-libraries/rust/testing',
        'client-libraries/rust/distributed-tracing',
      ],
    },
    {
      type: 'category',
      label: 'WebAssembly',
      link: { type: 'doc', id: 'client-libraries/wasm/wasm' },
      customProps: {
        iconLight: '/img/wasm-logo.svg',
        iconDark: '/img/wasm-logo.svg',
        iconType: 'img',
      },
      items: [
        'client-libraries/wasm/wasm',
      ],
    },
  ],

  // ---- Guides tab ---------------------------------------------------------
  guidesSidebar: [
    {
      type: 'html',
      value: 'Guides',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    { type: 'autogenerated', dirName: 'guides' },
  ],

  // ---- Reference tab (everything else) ------------------------------------
  referenceSidebar: [
    {
      type: 'html',
      value: 'Data & internals',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    { type: 'doc', id: 'components/components', label: 'Components' },
    'components/schemas/schemas',
    {
      type: 'category',
      label: 'Predicates',
      customProps: sbIcon('filter'),
      link: { type: 'doc', id: 'components/predicates/predicates' },
      items: ['components/predicates/quick-reference'],
    },
    {
      type: 'category',
      label: 'Persistence in Ahnlich',
      customProps: sbIcon('save'),
      link: { type: 'doc', id: 'components/persistence-in-ahnlich/persistence-in-ahnlich' },
      items: [
        'components/persistence-in-ahnlich/persistence-for-ahnlich-db',
        'components/persistence-in-ahnlich/persistence-for-ahnlich-ai',
      ],
    },
    {
      type: 'category',
      label: 'Distributed Tracing',
      customProps: sbIcon('branch'),
      link: { type: 'doc', id: 'components/distributed-tracing/distributed-tracing' },
      items: [
        'components/distributed-tracing/ahnlich-db',
        'components/distributed-tracing/ahnlich-ai',
        'components/distributed-tracing/using-jaeger',
      ],
    },
    {
      type: 'html',
      value: 'Operations',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    {
      type: 'category',
      label: 'Ahnlich in production',
      customProps: sbIcon('zap'),
      items: [{ type: 'autogenerated', dirName: 'ahnlich-in-production' }],
    },
    {
      type: 'category',
      label: 'Reference',
      customProps: sbIcon('bookOpen'),
      items: ['reference/error-codes', 'reference/configuration'],
    },
    {
      type: 'category',
      label: 'Troubleshooting',
      customProps: sbIcon('wrench'),
      items: ['troubleshooting/common-issues'],
    },
    {
      type: 'html',
      value: 'Project',
      className: 'sidebar-section-title',
      defaultStyle: true,
    },
    'architecture',
    'community',
  ],
};

export default sidebars;
